### PR TITLE
Add "name" property when in development mode

### LINKED ISSUE #1: Option to add "name" property
Adding `name` property could help in debugging your application. This could be defined as option for plugin so it isn’t active by default.

What do you think?

### PR DESCRIPTION
**Pull request by niksy**
Closes #1.

### CODE REVIEW

**Comment by nickmessing** [comment]
@niksy, looks good but isn't approach of conditional `unshift`ing easier to read?
like:
```js
const a = [1, 2]
condition && a.unshift(0)
```
?

When I walk through your code the piece that is or is not in array is far from conditional check and you can't read it top-to-bottom which potentially makes it harder to understand IMO. What do you think?

**Comment by niksy** [comment]
@nickmessing definitely, but I was trying to follow [your proposal](https://github.com/nickmessing/babel-plugin-jsx-vue-functional/issues/1#issuecomment-302555359) where `name` is second property (although that doesn’t really matter I suppose, since this is only for development purposes). I’ve changed the code a little bit so instead of removing the item from specific index, it inserts it at that index. If you’re still think that mentally this isn’t best approach, I would change to `unshift` approach.

**Comment by nickmessing** [comment]
@niksy, as you said, it doesn't matter if it's second parameter since browsers don't care about order of keys in object (actually they care with `Object.{keys|entries|values}`) but there is no guarantee it's going to be in order of declaration so both `unshift` and `push` should work fine, I just want the code to be as easy to follow as possible, thank you for your time.

**Comment by nickmessing** [comment]
@niksy, btw, just released 2.0.0 solving #2, looks like you'll need to rebase

**Comment by nickmessing** [comment]
Good job

**Pull request merged**
